version: '3.8'

services:
  # Node.js Server (Frontend)
  node-server:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "${NODE_PORT:-3000}:${NODE_PORT:-3000}"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - NODE_SERVER_URL=http://node-server:${NODE_PORT:-3000}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    depends_on:
      - temporal
    networks:
      - cipc-network

  # Go Worker (Backend)
  go-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - NODE_SERVER_URL=http://node-server:${NODE_PORT:-3000}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    depends_on:
      - temporal
      - node-server
    networks:
      - cipc-network

  # Temporal Server
  temporal:
    image: temporalio/auto-setup:1.21.0
    ports:
      - "${TEMPORAL_ADDRESS:-localhost:7233}:7233" # gRPC frontend
      - "${TEMPORal_UI_PORT:-8233}:8233" # Web UI
    environment:
      - DB=sqlite3
      - TEMPORAL_BROADCAST_ADDRESS=temporal
    networks:
      - cipc-network

networks:
  cipc-network:
    driver: bridge
