services:
  # PostgreSQL Database Service
  db:
    image: postgres:16-alpine
    container_name: cipc-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # This should be sourced from .env in production
      POSTGRES_DB: cipc_agent
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cipc-network
    restart: unless-stopped

  # Node.js Backend Service
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: cipc-server
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - cipc-network
    restart: unless-stopped

  # React Frontend Service
  client:
    build: ./client
    container_name: cipc-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - cipc-network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  cipc-network:
    driver: bridge
