name: 🚀 CI & CD
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    services:
      cockroach:
        image: cockroachdb/cockroach:v23.2
        ports: ["26257:26257"]
        env:
          COCKROACH_USER: root
          COCKROACH_DATABASE: cipc_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - name: 🧪 Lint
        uses: golangci/golangci-lint-action@v6
        with: { args: "--timeout=3m" }
      - name: 🧪 Unit Tests
        run: go test ./... -coverprofile=cover.out
      - name: 📦 Build Docker image
        run: |
          docker build -t cipc-api:${{ github.sha }} .
  deploy-staging:
    needs: lint-test-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: 🚀 Deploy to Fly.io staging
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          args: "deploy --app cipc-agent-staging --image cipc-api:${{ github.sha }}"
  deploy-prod:
    needs: lint-test-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: 🚀 Deploy to Fly.io prod
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          args: "deploy --app cipc-agent-prod --image cipc-api:${{ github.sha }}"