name: Client CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab or via the GitHub CLI
  workflow_dispatch:

jobs:
  client-build-and-test:
    name: Build and Test Client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Based on the `engines` field in your dependencies (e.g., react-hook-form)
        node-version: [ '18.x', '20.x' ]

    defaults:
      run:
        # Assuming your client-side code and package.json are in the `client` directory
        working-directory: ./client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build